### PR TITLE
Simplify more things

### PR DESCRIPTION
**Pull request by GenesisTP**

### CODE REVIEW

**Comment by TagProKrieger** [comment]
On second thought, it'd probably be a good idea to update the maps while I'm at it.

**Comment by TagProKrieger** [comment]
I just realized Wombo Combo's preview uses a different texture pack but I'm too lazy to close this PR

**Comment by GenesisTP** [comment]
I'm pretty sure this is all for the time being, but I'm not going to move this into the main subreddit until there's enough room in the stylesheet. I actually have a version that's over 10 KB smaller up on [my test sub](//reddit.com/r/TagProKrieger), but I'm waiting until I can fix some really tiny and irrelevant issues before then.

**Comment by ylambda** [comment]
Woah, that's awesome. Also I'm alright with removing the giant comment block at the top or trimming it, compressing more or all of the stylesheet, and any other tweaks.

I'm going to add you as a contributor to this repository so you can approve patches.

**Pull request merged**
