### PR TITLE
Clean some things up

### PR DESCRIPTION
**Pull request by GenesisTP**
I went back to committing from the command line so these commits aren't completely terrible now

Anyway, here's some other stuff I'd like to change if it's OK with you:
1. Can we make FFmpeg's location in create_map_sprites an environment variable? About 99.7% of people don't have home directories named `ylambda`, and it'd probably be a good idea to accommodate them.
2. Can we get rid of the wooden hammer developer flair? I'm pretty sure the only place it's used is in one really outdated wiki page, and it's not even in the [in-game flair sprite](//tagpro-diameter.koalabeast.com/images/flair.png) anymore.
3. Can we change the MLTP flair class names to not rely on Roman numerals? [Unless I'm missing something](//www.reddit.com/message/messages/3dsphx), the argument against doing so basically sounds exactly like the argument against implementing ties.

### CODE REVIEW

**Comment by ylambda** [comment]
1. Absolutely.
2. Yeah, that's fine with me
3. I dunno. We'd have to update everyone who has their css flair `I`, `II`, `III`. We could just change it and see if anyone notices or make a post to explain. What do you think?

**Comment by ylambda** [comment]
BTW this is a great pull-request.

**Comment by GenesisTP** [comment]
Thanks!

Does that even have to be a problem for 3, though? Couldn't we just use PRAW to update users' flair classes automatically?

I guess it might be a little more problematic with flair within Markdown: the wiki could be updated without too much trouble (and I've already written a dinky script for this and the user flair), but it'd be impossible to do anything about user-generated posts. Then again, no one really uses this feature, and I don't really think it's enough to keep us from moving to a better syntax.

**Comment by ylambda** [comment]
I wouldn't worry about user posts. PRAW is a great idea. That should work.

**Comment by GenesisTP** [comment]
OK, I've updated the Roman numerals on the sub. Also this: https://github.com/ylambda/tagpro-subreddit-css/pull/5

**Pull request merged**
